#!/usr/bin/env bash
set -euo pipefail

package="$(cd "$(dirname "$0")/.." && pwd)"
output="$package/generated/coacd"
build="$(mktemp -d)"
trap 'rm -rf "$build"' EXIT

# Changing a pin changes the decomposer: bump DECOMPOSER in src/decomposition.ts too.
coacd=b678aa0802996fa03e1ec0e68bd05acf8cd20cf9
cdt=ec03b309fd18102ab1da069f2edf3b37be5d1fb3
bridge=5a969983b1a1280c07b2c7cdf44c16a681fc3384
sdk=c817c0ca4ba889ee24a185fd954cff7de1bd8afa

for command in curl tar cmake node python3; do
  command -v "$command" >/dev/null
done

fetch() {
  curl --fail --location --retry 3 --silent --show-error "$1" --output "$2"
}

extract() {
  fetch "https://codeload.github.com/$1/tar.gz/$2" "$build/archive.tar.gz"
  mkdir -p "$3"
  tar -xzf "$build/archive.tar.gz" --strip-components=1 -C "$3"
}

# Reuse the pinned compiler when installed; otherwise bootstrap it locally.
compiler="$(command -v em++ || true)"
if [[ -z "$compiler" || "$("$compiler" --version)" != *"5.0.2"* ]]; then
  extract emscripten-core/emsdk "$sdk" "$build/emsdk"
  "$build/emsdk/emsdk" install 5.0.2
  "$build/emsdk/emsdk" activate 5.0.2
  source "$build/emsdk/emsdk_env.sh"
fi

extract SarahWeiii/CoACD "$coacd" "$build/source/coacd"
extract artem-ogre/CDT "$cdt" "$build/source/coacd/3rd/cdt"
mkdir -p "$build/source/bridge" "$build/output/licenses"
fetch "https://raw.githubusercontent.com/Autarkis/chitin/$bridge/integrations/wasm/src/coacd_bind.cpp" "$build/source/bridge/coacd_bind.cpp"
fetch "https://raw.githubusercontent.com/Autarkis/chitin/$bridge/LICENSE" "$build/source/bridge/LICENSE"
fetch "https://raw.githubusercontent.com/spdx/license-list-data/v3.26.0/text/LGPL-2.1-only.txt" "$build/output/licenses/LGPL-2.1.txt"

emcmake cmake -S "$build/source/coacd" -B "$build/objects" \
  -DWITH_3RD_PARTY_LIBS=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_SKIP_INSTALL_RULES=ON
cmake --build "$build/objects" --target coacd --parallel
em++ -O3 -sMODULARIZE=1 -sEXPORT_ES6=1 -sALLOW_MEMORY_GROWTH=1 \
  -sSINGLE_FILE=1 -sSINGLE_FILE_BINARY_ENCODE=0 -sFILESYSTEM=0 \
  -sINITIAL_MEMORY=67108864 -sENVIRONMENT=web,worker,node --bind -std=c++20 \
  --emit-tsd "$build/output/coacd.d.ts" \
  -I"$build/source/coacd/public" "$build/source/bridge/coacd_bind.cpp" \
  "$build/objects/libcoacd.a" -o "$build/output/coacd.js"

python3 - "$build/output" <<'PY'
from pathlib import Path
import sys

output = Path(sys.argv[1])
javascript = (output / "coacd.js").read_text()
declarations = (output / "coacd.d.ts").read_text()
export = "export default Module;"
factory = "export default function MainModuleFactory (options?: unknown): Promise<MainModule>;"
if javascript.count(export) != 1 or declarations.count(factory) != 1:
    raise RuntimeError("Unexpected Emscripten module format")
source = "// @ts-nocheck -- Generated Emscripten internals; public API types are generated by --emit-tsd.\n"
source += javascript.replace(export, "") + "\n"
source += declarations.replace(factory, "")
source += "\nconst createCoACD: (options?: unknown) => Promise<MainModule> = Module;\n"
source += "export default createCoACD;\n"
(output / "coacd.ts").write_text(source)
(output / "coacd.js").unlink()
(output / "coacd.d.ts").unlink()
PY

cp "$build/source/coacd/LICENSE" "$build/output/LICENSE"
cp "$build/source/bridge/LICENSE" "$build/output/licenses/Chitin.txt"
cp "$build/source/coacd/3rd/cdt/LICENSE" "$build/output/licenses/CDT.txt"
sed -n '1,/\*\//p' "$build/source/coacd/src/btConvexHull/btConvexHullComputer.h" > "$build/output/licenses/Bullet.txt"
cp "$0" "$build/source/build-coacd.sh"
tar -czf "$build/output/source.tar.gz" -C "$build/source" \
  build-coacd.sh bridge coacd/CMakeLists.txt coacd/LICENSE coacd/README.md \
  coacd/cmake coacd/public coacd/src coacd/3rd/cdt/CDT/include \
  coacd/3rd/cdt/LICENSE coacd/3rd/cdt/CDT/LICENSE
cat > "$build/output/README.md" <<EOF
# Generated CoACD WASM

Built by scripts/build-coacd.sh with Emscripten 5.0.2.
src/coacd.ts embeds its WASM and is compiled to dist/coacd.js.
No external asset is required.

Source revisions:
- https://github.com/SarahWeiii/CoACD/tree/$coacd
- https://github.com/artem-ogre/CDT/tree/$cdt
- https://github.com/Autarkis/chitin/tree/$bridge/integrations/wasm

The source archive and license notices accompany the native binary, including
CDT (MPL-2.0) and John Burkardt's Sobol routines (LGPL). They are not imported
by the runtime or included in application JavaScript bundles.
EOF

# Publish a complete build only after compilation and packaging succeed.
mkdir -p "$(dirname "$output")"
mv "$build/output/coacd.ts" "$package/src/coacd.ts"
rm -rf "$output"
mv "$build/output" "$output"
